name: 'build'
on:   ['push', 'pull_request']
jobs:
  cross-compile:
    strategy:
      fail-fast: false
      matrix:
        go: ['1.16', '1.19']
    runs-on: ubuntu-latest
    steps:
      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: |
          for a in $(go tool dist list); do
            GOOS=${a%%/*} GOARCH=${a#*/} go build
          done
