name: 'build'
on:
  push:
    paths: ['**.go', 'go.mod', '.github/workflows/*']

jobs:
  cross-compile:
    strategy:
      fail-fast: false
      matrix:
        go: ['1.16', '1.19']
    runs-on: ubuntu-latest
    steps:
      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: checkout
        uses: actions/checkout@v3

      - name: build
        run: |
          set -x
          for a in $(go tool dist list); do
            export GOOS=${a%%/*}
            export GOARCH=${a#*/}

            go test -c
            # Building for Android or iOS requires cgo
            if [ "$GOOS" != 'android' ] && [ "$GOOS" != 'ios' ]; then
              go build ./cmd/fsnotify
            fi
          done
