name: slow-tests
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-illumos:
    runs-on: macos-10.15
    name: Test in illumos VM
    steps:
    - uses: actions/checkout@v2
    - name: Test on illumos
      id: test
      uses: papertigers/illumos-vm@r38
      with:
        prepare: |
          pkg install go-117
        run: |
          /opt/ooce/go-1.17/bin/go test -count=10
