#name: 'test-qemu'
on:
  push:
    paths: ['**.go', 'go.mod', '.github/workflows/*']

jobs:
  test-qemu:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - '386'
          - 'arm'
          - 'arm64'
          - 'mips'
          - 'mips64'
          - 'mips64le'
          - 'mipsle'
          - 'ppc64'
          - 'ppc64le'
          - 'riscv64'
          - 's390x'

    # QEMU only works on Linux for now, and use Ubuntu 22.04 to get a
    # reasonably recent version of QEMU.
    runs-on: ubuntu-22.04
    steps:
      - name: Setup QEMU
        run: |
          sudo apt-get install -y qemu-user

      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: checkout
        uses: actions/checkout@v3

      - name: 'ubuntu ${{ matrix.arch }}'
        run: |
          GOARCH=${{ matrix.arch }} ./.github/workflows/test-archs.sh
