name: vagrant
on:
  push:
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian6
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: test
        run: |
          cp -f .github/workflows/Vagrantfile.${{ matrix.image }} Vagrantfile
          GOOS=linux GOARCH=amd64 go test -o fsnotify.test -c ./...
          vagrant up
          vagrant ssh -c "/vagrant/fsnotify.test"
